"""Exporters: OrcaSlicer/Bambu 3MF project, STL zip, GLB for the web preview.

3MF layout (matched against projects saved by OrcaSlicer 2.x / Bambu Studio 2.x):

    [Content_Types].xml
    _rels/.rels                         -> 3D/3dmodel.model (+ thumbnail)
    3D/3dmodel.model                    one object made of components, one build item
    3D/_rels/3dmodel.model.rels         -> 3D/Objects/object_1.model
    3D/Objects/object_1.model           one mesh object per part (per filament)
    Metadata/model_settings.config      object + part names, per-part "extruder" (AMS slot)
    Metadata/slice_info.config          producer header
    Metadata/plate_1.png                thumbnail (the preview)

No Metadata/project_settings.config is written. OrcaSlicer layers a project config over
its generic defaults, so a partial one would replace the user's printer profile. The
file also carries no "OrcaSlicer" version tag: Orca treats a tagged file without a
project config as broken (its CLI crashes on it), while an untagged file is imported as
a third-party 3MF that keeps the object, the part names and each part's filament slot.
Verified by round-tripping through the OrcaSlicer 2.5 CLI (--export-3mf and --slice).
The user's own printer and AMS filament presets stay in place.
"""

from __future__ import annotations

import io
import zipfile
from datetime import date
from xml.sax.saxutils import escape, quoteattr

import numpy as np

from . import __version__
from .pipeline import ReliefResult

APPLICATION = f"LayerLift-{__version__}"
OBJECT_UUID_SUFFIX = "-61cb-4c03-9d28-80fed5dfa1dc"
SUB_OBJECT_UUID_SUFFIX = "-81cb-4c03-9d28-80fed5dfa1dc"
COMPONENT_UUID_SUFFIX = "-b206-40ff-9872-83e8017abed1"
BUILD_UUID = "2c7c17d8-22b5-4d84-8835-1976022ea369"
BUILD_UUID_SUFFIX = "-b1ec-4553-aec9-835e5b724bb4"
IDENTITY_4X4 = "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"

NS = (
    'unit="millimeter" xml:lang="en-US" '
    'xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" '
    'xmlns:BambuStudio="http://schemas.bambulab.com/package/2021" '
    'xmlns:p="http://schemas.microsoft.com/3dmanufacturing/production/2015/06" '
    'requiredextensions="p"'
)


def part_label(result: ReliefResult, part) -> str:
    return f"{part.filament + 1:02d} {part.name}"


def _centre_offset(result: ReliefResult) -> np.ndarray:
    lo = np.min([p.mesh.bounds[0] for p in result.parts], axis=0)
    hi = np.max([p.mesh.bounds[1] for p in result.parts], axis=0)
    return np.array([-(lo[0] + hi[0]) / 2, -(lo[1] + hi[1]) / 2, -lo[2]])


def _fmt(v: float) -> str:
    s = f"{v:.6f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def _mesh_xml(mesh, offset: np.ndarray) -> str:
    v = np.asarray(mesh.vertices) + offset
    f = np.asarray(mesh.faces)
    out = ["    <mesh>\n     <vertices>\n"]
    out.extend(f'      <vertex x="{_fmt(x)}" y="{_fmt(y)}" z="{_fmt(z)}"/>\n' for x, y, z in v)
    out.append("     </vertices>\n     <triangles>\n")
    out.extend(f'      <triangle v1="{a}" v2="{b}" v3="{c}"/>\n' for a, b, c in f)
    out.append("     </triangles>\n    </mesh>\n")
    return "".join(out)


def export_3mf(
    result: ReliefResult,
    title: str = "LayerLift relief",
    thumbnail_png: bytes | None = None,
    plate_centre: tuple[float, float] = (128.0, 128.0),
) -> bytes:
    """Write a single-object, multi-part 3MF with each part pre-assigned to its filament slot."""
    if not result.parts:
        raise ValueError("nothing to export")
    offset = _centre_offset(result)
    n = len(result.parts)
    obj_id = n + 1
    cx, cy = plate_centre
    today = date.today().isoformat()

    # --- 3D/Objects/object_1.model: one mesh object per part
    sub = [f'<?xml version="1.0" encoding="UTF-8"?>\n<model {NS}>\n <metadata name="BambuStudio:3mfVersion">1</metadata>\n <resources>\n']
    for i, part in enumerate(result.parts, start=1):
        sub.append(f'  <object id="{i}" p:UUID="{(1 << 16) + i - 1:08x}{SUB_OBJECT_UUID_SUFFIX}" type="model">\n')
        sub.append(_mesh_xml(part.mesh, offset))
        sub.append("  </object>\n")
    sub.append(" </resources>\n <build/>\n</model>\n")

    # --- 3D/3dmodel.model: the assembly object and its build item
    meta = {
        "Application": APPLICATION,
        "BambuStudio:3mfVersion": "1",
        "Title": title,
        "Designer": "",
        "Description": "Multi-colour relief generated by LayerLift. Each part is pre-assigned to a filament slot.",
        "CreationDate": today,
        "ModificationDate": today,
    }
    main = [f'<?xml version="1.0" encoding="UTF-8"?>\n<model {NS}>\n']
    main.extend(f" <metadata name={quoteattr(k)}>{escape(v)}</metadata>\n" for k, v in meta.items())
    main.append(" <resources>\n")
    main.append(f'  <object id="{obj_id}" p:UUID="{1:08x}{OBJECT_UUID_SUFFIX}" type="model">\n   <components>\n')
    for i in range(1, n + 1):
        main.append(
            f'    <component p:path="/3D/Objects/object_1.model" objectid="{i}" '
            f'p:UUID="{(1 << 16) + i - 1:08x}{COMPONENT_UUID_SUFFIX}" transform="1 0 0 0 1 0 0 0 1 0 0 0"/>\n'
        )
    main.append("   </components>\n  </object>\n </resources>\n")
    main.append(f' <build p:UUID="{BUILD_UUID}">\n')
    main.append(
        f'  <item objectid="{obj_id}" p:UUID="{obj_id:08x}{BUILD_UUID_SUFFIX}" '
        f'transform="1 0 0 0 1 0 0 0 1 {_fmt(cx)} {_fmt(cy)} 0" printable="1"/>\n'
    )
    main.append(" </build>\n</model>\n")

    # --- Metadata/model_settings.config: names and filament slot per part
    ms = ['<?xml version="1.0" encoding="UTF-8"?>\n<config>\n']
    ms.append(f'  <object id="{obj_id}">\n')
    ms.append(f"    <metadata key=\"name\" value={quoteattr(title)}/>\n")
    ms.append('    <metadata key="extruder" value="1"/>\n')
    ms.append(f'    <metadata face_count="{sum(len(p.mesh.faces) for p in result.parts)}"/>\n')
    for i, part in enumerate(result.parts, start=1):
        ms.append(f'    <part id="{i}" subtype="normal_part">\n')
        ms.append(f"      <metadata key=\"name\" value={quoteattr(part_label(result, part))}/>\n")
        ms.append(f'      <metadata key="matrix" value="{IDENTITY_4X4}"/>\n')
        ms.append(f'      <metadata key="extruder" value="{part.filament + 1}"/>\n')
        ms.append(
            f'      <mesh_stat face_count="{len(part.mesh.faces)}" edges_fixed="0" degenerate_facets="0" '
            'facets_removed="0" facets_reversed="0" backwards_edges="0"/>\n'
        )
        ms.append("    </part>\n")
    ms.append("  </object>\n")
    ms.append(
        "  <plate>\n"
        '    <metadata key="plater_id" value="1"/>\n'
        '    <metadata key="plater_name" value=""/>\n'
        '    <metadata key="locked" value="false"/>\n'
    )
    if thumbnail_png:
        ms.append('    <metadata key="thumbnail_file" value="Metadata/plate_1.png"/>\n')
    ms.append(
        "    <model_instance>\n"
        f'      <metadata key="object_id" value="{obj_id}"/>\n'
        '      <metadata key="instance_id" value="0"/>\n'
        '      <metadata key="identify_id" value="1"/>\n'
        "    </model_instance>\n"
        "  </plate>\n"
        "  <assemble>\n"
        f'   <assemble_item object_id="{obj_id}" instance_id="0" transform="1 0 0 0 1 0 0 0 1 {_fmt(cx)} {_fmt(cy)} 0" offset="0 0 0" />\n'
        "  </assemble>\n"
        "</config>\n"
    )

    content_types = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">\n'
        ' <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>\n'
        ' <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>\n'
        ' <Default Extension="png" ContentType="image/png"/>\n'
        ' <Default Extension="gcode" ContentType="text/x.gcode"/>\n'
        "</Types>\n"
    )
    rels = [
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">\n'
        ' <Relationship Target="/3D/3dmodel.model" Id="rel-1" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>\n'
    ]
    if thumbnail_png:
        rels.append(
            ' <Relationship Target="/Metadata/plate_1.png" Id="rel-2" '
            'Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/thumbnail"/>\n'
        )
    rels.append("</Relationships>\n")
    model_rels = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">\n'
        ' <Relationship Target="/3D/Objects/object_1.model" Id="rel-1" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>\n'
        "</Relationships>\n"
    )
    slice_info = (
        '<?xml version="1.0" encoding="UTF-8"?>\n<config>\n  <header>\n'
        '    <header_item key="X-BBL-Client-Type" value="slicer"/>\n'
        '    <header_item key="X-BBL-Client-Version" value=""/>\n'
        "  </header>\n</config>\n"
    )

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml", content_types)
        z.writestr("_rels/.rels", "".join(rels))
        z.writestr("3D/3dmodel.model", "".join(main))
        z.writestr("3D/_rels/3dmodel.model.rels", model_rels)
        z.writestr("3D/Objects/object_1.model", "".join(sub))
        z.writestr("Metadata/model_settings.config", "".join(ms))
        z.writestr("Metadata/slice_info.config", slice_info)
        if thumbnail_png:
            z.writestr("Metadata/plate_1.png", thumbnail_png)
    return buf.getvalue()


def summary_text(result: ReliefResult, title: str) -> str:
    lines = [
        f"{title}",
        "",
        f"Size: {result.size_mm[0]:.1f} x {result.size_mm[1]:.1f} x {result.size_mm[2]:.1f} mm",
        f"Layer height: {result.layer_mm:g} mm   Base: {result.base_mm:g} mm ({result.filaments[result.base_filament].name})",
        f"Estimated filament changes: {result.changes.total}",
        "",
        "Slot  Filament              Colour    Top (mm)   Grams",
    ]
    for p in result.parts:
        lines.append(f"{p.filament + 1:>4}  {p.name[:20]:<20}  {p.hex:<8}  {p.z_max:>8.2f}  {p.grams:>6.1f}")
    lines += ["", "Load all STL files together and answer 'Yes' when asked to load them as a single object", "with multiple parts, then assign each part to the slot shown above."]
    return "\n".join(lines) + "\n"


def export_stl_zip(result: ReliefResult, title: str = "relief") -> bytes:
    """One binary STL per filament (shared coordinates, so they align when loaded together)."""
    offset = _centre_offset(result)
    safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in title) or "relief"
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for part in result.parts:
            m = part.mesh.copy()
            m.apply_translation(offset)
            name = "".join(c if c.isalnum() or c in "-_" else "_" for c in part.name)
            z.writestr(f"{safe}_{part.filament + 1:02d}_{name}.stl", m.export(file_type="stl"))
        z.writestr("README.txt", summary_text(result, title))
    return buf.getvalue()


def export_glb(result: ReliefResult) -> bytes:
    """GLB with one coloured node per part, for the three.js preview (Z-up millimetres)."""
    import trimesh

    offset = _centre_offset(result)
    scene = trimesh.Scene()
    for part in result.parts:
        m = part.mesh.copy()
        m.apply_translation(offset)
        # glTF colour factors are linear; convert from sRGB so viewers show the true colour.
        srgb = np.array([int(part.hex[i : i + 2], 16) for i in (1, 3, 5)]) / 255.0
        linear = np.where(srgb <= 0.04045, srgb / 12.92, ((srgb + 0.055) / 1.055) ** 2.4)
        material = trimesh.visual.material.PBRMaterial(
            name=part.name, baseColorFactor=[*linear.tolist(), 1.0], metallicFactor=0.0, roughnessFactor=0.8
        )
        m.visual = trimesh.visual.TextureVisuals(material=material)
        scene.add_geometry(m, node_name=f"part_{part.filament}", geom_name=f"part_{part.filament}")
    return scene.export(file_type="glb")
